- hosts: all
  tasks:
  - name: group hosts by os version
    group_by: key={{ansible_distribution}}-{{ansible_distribution_version}}

- hosts: tomcat-servers
  tasks:
  - name: ping all hosts
    ping:
